services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "lostnfound_dev"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local
