version: '3.8'
services:
  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
  #     PHOENIX_HOST: ${PHOENIX_HOST}
  #     SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  #     PHX_SERVER: ${PHX_SERVER}
  #     JWT_SECRET: ${JWT_SECRET}
  #   depends_on:
  #     - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
